<a href="https://colab.research.google.com/github/Kgodiso-Leboho/GameVault-Aquisition-Intelligence-System/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [32]:
df = pd.read_csv('/content/sample_data/steam_reviews 1.csv')

In [33]:
df.head()

,date_posted,funny,helpful,hour_played,is_early_access_review,recommendation,review,title
0,2018-11-24,0,0,40,False,Recommended,10/10 would murder kids again,Rust
1,2016-06-28,0,0,20,False,Recommended,OH YEAH,Euro Truck Simulator 2
2,2016-01-09,0,0,292,True,Recommended,is good gam,Rust
3,2018-07-08,0,0,401,False,Recommended,Spooky.,Dead by Daylight
4,2018-12-29,1,1,125,False,Not Recommended,Tries to play for an hour with my bros.Had to ...,Grand Theft Auto V

In [34]:
print('The dataset contains ', df.shape[0], ' rows and ', df.shape[1], ' columns')

The dataset contains  14617  rows and  8  columns

In [35]:
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)

0

In [36]:
df.isnull().sum()

date_posted               0
funny                     0
helpful                   0
hour_played               0
is_early_access_review    0
recommendation            0
review                    7
title                     0
dtype: int64

In [38]:
# Calculate the proportion of missing values to the dataset
missing_values = df['review'].isnull().sum()
size = df.shape[0]
print((missing_values/df.shape[0])*100)

0.04788944379831703

In [9]:
df = df.dropna(subset=['review'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14610 entries, 0 to 14616
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date_posted             14610 non-null  object
 1   funny                   14610 non-null  int64
 2   helpful                 14610 non-null  int64
 3   hour_played             14610 non-null  int64
 4   is_early_access_review  14610 non-null  bool
 5   recommendation          14610 non-null  object
 6   review                  14610 non-null  object
 7   title                   14610 non-null  object
dtypes: bool(1), int64(3), object(4)
memory usage: 927.4+ KB

In [15]:
df['date_posted'] = pd.to_datetime(df['date_posted'])

/tmp/ipykernel_425/1368011919.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date_posted'] = pd.to_datetime(df['date_posted'])

In [43]:
df['review'] = df['review'].str.lower().str.strip()
df['title'] = df['title'].str.lower().str.strip()

In [45]:
df['funny'] = pd.to_numeric(df['funny'], errors='coerce')
df['helpful'] = pd.to_numeric(df['helpful'], errors='coerce')
df['hour_played'] = pd.to_numeric(df['hour_played'], errors='coerce')

In [24]:
df.groupby('recommendation')['hour_played'].mean()

recommendation
Not Recommended    261.095972
Recommended        310.363619
Name: hour_played, dtype: float64

In [46]:
valid_labels = ['Recommended', 'Not Recommended']
df =df[df['recommendation'].isin(valid_labels)]